FROM maven:3.8.6-openjdk-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package

FROM openjdk:11-jre-slim
COPY --from=build /app/target/Calculator-SPE-1.0-SNAPSHOT-jar-with-dependencies.jar /app.jar
CMD ["java", "-jar", "/app.jar"]
