# Use OpenJDK 21 as the base image
FROM openjdk:21-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the host to the container
COPY target/Calculator-App-SPE-1.0-SNAPSHOT.jar /app/Calculator-App-SPE.jar

# Command to run the JAR file
CMD ["java", "-jar", "Calculator-App-SPE.jar"]
