pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = 'calculator-spe-hyma'        // Replace with your desired image name
    }
 
    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git 'https://github.com/HymaJayaram-067/Calculator.spe.git'  // Replace with your Git repository URL
            }
        }
 
        stage('Build with Maven') {
            steps {
                script {
                    // Navigate to the project folder and run Maven clean install
                    sh 'cd Calculator-App-SPE && mvn clean install'
                }
            }
        }
 
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    sh '''
                        cd Calculator-App-SPE
                        docker build -t $DOCKER_IMAGE_NAME .
                    '''
                }
            }
        }
 
        stage('Push Docker Image') {
            steps {
                script {
                    // Tag the Docker image
                    sh '''
                        docker tag $DOCKER_IMAGE_NAME hyma067/$DOCKER_IMAGE_NAME:latest1
                        docker push hyma067/$DOCKER_IMAGE_NAME:latest1
                    '''
                }
            }
        }
    }
 
    post {
        success {
            echo 'Build and Docker image push were successful!'
        }
        failure {
            echo 'Build or Docker image push failed.'
        }
    }
}
