---
- name: Deploy Calculator
  hosts: production
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: hymajayaram-067/calculator-spe:latest
        source: pull

    - name: Run container
      docker_container:
        name: calculator
        image: hymajayaram-067/calculator-spe:latest
        ports: "8080:8080"
        state: started
